引数なしの場合の仕様の追記
approvers/haracho.approvers.dev pull request #11
Opened 2023-01-19 04:35 UTC by raiga0310

close #

### 実施内容
ドキュメント内において，`dice`コマンドの仕様に関して記述されていない部分がありましたので追記を行いました．
### 追加情報
この仕様についての該当コード
https://github.com/approvers/OreOreBot2/blob/main/src/service/command/dice.ts#L35

2023-01-19 09:01 UTC, m1sk9 commented
@raiga0310 

(Merge には Prettier の実行が必要です、実行されていないと CI でコケます。開発サーバーでの確認など適切な手段を通っているなら husky によって実行されるはずですがお忘れなく)

2023-01-23 14:53 UTC, m2en commented
@raiga0310 

ベースブランチの変更が `docs-dice` にマージされていないので更新してください (このままApproveしても更新時にApproveが自動的に却下されます)

2023-01-23 14:55 UTC, m2en requested changes
ベースブランチの変更が docs-dice にマージされていないので更新してください (このままApproveしても更新時にApproveが自動的に却下されます)

2023-01-27 05:37 UTC, m2en submitted a review, later dismissed

2023-01-27 05:44 UTC, MikuroXina commented on docs/commands_docs/dice.mdx
> +- 補足: `!dice`の場合は`!dice 1d100`と同様の入力とみなされます。
```suggestion
- 補足: `!dice` の場合は `!dice 1d100` と同様の入力とみなされます。
```
他の文章と同じようにインラインコードの前後に記号または余白があるようにしたほうがよいかと, コードスタイルとして実施されてはいませんが

2023-01-28 04:47 UTC, m2en approved these changes

2023-01-28 05:25 UTC, merged